.TH "OpenLDev" "1" "1.0" "Andrew Krause" ""
.SH "NAME"
.LP
openldev \- Gtk+ Integrated Development Environment
.SH "SYNTAX"
.LP
openldev [\fIoption\fP]
.SH "DESCRIPTION"
.LP
OpenLDev is a graphical front-end to Linux development tools such as gcc, autotools and make. Most Integrated Development Environments (IDE), are cumbersome and confusing to use, but OpenLDev strives to provide an easy-to-use interface that is both productive for experts and simple for beginners.
.SH "OPTIONS"
.LP
\fB\-\-help, \-?\fR
Output help information and exit.
.TP
\fB\-\-version\fR
Output version information and exit.
.SH "AUTHORS"
.LP
This man page was written by Andrew Krause <\fIandrew@openldev.org\fP>. For more information, visit <\fIwww.openldev.org\fP>.
